### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by FlatKey** [MaibornWolff/dcos-thanos#2]
If I try to deploy the new release Version 0.1.2 I've got the following Error in the instance task:
`2021/04/22 16:53:20 SDK Bootstrap successful.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/mesosphere/sdk/operator/scheduler/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
I0422 16:53:20.839504     8 executor.cpp:1041] Command exited with status 1 (pid: 12)
I0422 16:53:21.842144     2 checker_process.cpp:281] Stopped HTTP health check for task 'monitoring.instance-e5989b13-a38a-11eb-9012-46859e5a2595._app.15'
I0422 16:53:21.842505     2 process.cpp:935] Stopped the socket accept loop
`
What can I do to be able to deploy the new package version? Used DC/OS Version is 2.0.6.

**Comment by FlatKey** [comment]
I've tested a package which was build with the runner imager ubuntu-18.04 (Java 8 instead 11) and it works now.

**Comment by swoehrl-mw** [comment]
I have just released v0.1.3 built with java 8. Can you please try if that works for you?
